# The plugin's reload message. This is the only message in the plugin.
reload-message: "<gradient:#E6F9FF:#8FD9FB>[DimensionFishing] <white>Successfully reloaded the plugin."

# Configuration for lava fishing.
lava:
  # Which worlds is lava fishing enabled in?
  allowed-worlds:
    - world_nether

  # Which sound should play when the hook is swallowed by lava?
  # The hook is swallowed if the fish is not caught in time.
  swallow-sound: BLOCK_LAVA_EXTINGUISH

  # Which sound should play when the hook splashes into the lava?
  splash-sound: ENTITY_FISHING_BOBBER_SPLASH,0.25,0.5

  # Which particles should show while the fish is being lured?
  # Particle can be any of these values: https://jd.papermc.io/paper/26.1.2/org/bukkit/Particle.html
  # Amount is the amount shown and can be any valid integer.
  # Color is the color of the particle, and has to be a hex code. Not all particles support this config.
  lure-particles:
    - particle: LAVA
      amount: 3