# Configuration for DimensionFishing.
# See the EvenMoreFish Wiki for detailed explanations: https://evenmorefish.github.io/EvenMoreFish/docs/addons/dimensionfishing/setup

# The plugin's reload message. This is the only message in the plugin.
reload-message: "<gradient:#E6F9FF:#8FD9FB>[DimensionFishing] <white>Successfully reloaded the plugin."

# Configuration for lava fishing.
lava:
  # The permission the player needs to fish in lava.
  permission: []

  # Which worlds is lava fishing enabled in?
  # If this is empty, it will default to any world with the nether environment.
  allowed-worlds: []

  # Which sound should play when the hook is swallowed by lava?
  # The hook is swallowed if the fish is not caught in time.
  swallow-sound: BLOCK_LAVA_EXTINGUISH

  # Which sound should play when the hook is bitten by a fish?
  bite-sound: ENTITY_FISHING_BOBBER_SPLASH,0.25,0.5

  # Which particles should show while the fish is being lured?
  lure-particles:
    - particle: LAVA
      amount: 3

# Configuration for void fishing.
void:
  # The permission the player needs to fish in the void.
  permission: []

  # Which worlds is void fishing enabled in?
  # If this is empty, it will default to any world with the end environment.
  allowed-worlds: []

  # Which sound should play when the hook is swallowed by the void?
  # The hook is swallowed if the fish is not caught in time.
  swallow-sound: ENTITY_ENDERMAN_TELEPORT,0.25,0.1

  # Which sound should play when the hook is bitten by a fish?
  bite-sound: ENTITY_FOX_BITE,0.25,0.1

  # Which particles should show while the fish is being lured?
  # See [wiki doesn't exist yet] for a full explanation of this config.
  lure-particles:
    - particle: DUST
      amount: 3
      color: "#FF55FF"